from pydantic import BaseModel
from typing import Optional, List, Dict, Any


class StudioState(BaseModel):
    user_input: str
    active_project: Optional[str] = None
    active_agents: List[str] = []
    task_status: str = "pending"
    notes: Optional[str] = None
    project_path: Optional[str] = None
    loaded_context: Dict[str, str] = {}
    # Optional normalized project memory snapshot produced by the core
    # memory engine. Existing callers can continue to rely on loaded_context.
    normalized_memory: Dict[str, Any] = {}
    architect_plan: Optional[Dict[str, Any]] = None
    task_queue: List[Dict[str, Any]] = []
    # Optional richer snapshot for Nexus task queue engine; mirrors task_queue
    # but can evolve independently without breaking existing consumers.
    task_queue_snapshot: List[Dict[str, Any]] = []
    current_task: int = 0

    coder_output_path: Optional[str] = None
    implementation_file_path: Optional[str] = None
    test_report_path: Optional[str] = None
    docs_output_path: Optional[str] = None
    execution_report_path: Optional[str] = None
    workspace_report_path: Optional[str] = None
    operator_log_path: Optional[str] = None
    supervisor_report_path: Optional[str] = None
    studio_supervisor_report_path: Optional[str] = None
    autonomous_cycle_report_path: Optional[str] = None
    computer_use_report_path: Optional[str] = None
    tool_execution_report_path: Optional[str] = None
    file_modification_report_path: Optional[str] = None
    diff_patch_report_path: Optional[str] = None
    agent_routing_report_path: Optional[str] = None
    execution_bridge_report_path: Optional[str] = None
    engine_registry_report_path: Optional[str] = None
    capability_registry_report_path: Optional[str] = None
    tool_registry_report_path: Optional[str] = None
    workspace_boundary_report_path: Optional[str] = None
    path_migration_report_path: Optional[str] = None
    terminal_report_path: Optional[str] = None
    browser_research_report_path: Optional[str] = None
    full_automation_report_path: Optional[str] = None
    persistent_state_path: Optional[str] = None
    execution_ledger_path: Optional[str] = None
    run_id: Optional[str] = None
    execution_session_summary: Dict[str, Any] = {}

    previous_run_state: Dict[str, Any] = {}
    supervisor_decision: Dict[str, Any] = {}
    studio_supervisor_summary: List[Dict[str, Any]] = []
    autonomous_cycle_summary: Dict[str, Any] = {}
    computer_use_summary: Dict[str, Any] = {}
    tool_execution_summary: Dict[str, Any] = {}
    file_modification_summary: Dict[str, Any] = {}
    diff_patch_summary: Dict[str, Any] = {}
    agent_routing_summary: Dict[str, Any] = {}
    agent_profile: Dict[str, Any] = {}
    agent_selection_summary: Dict[str, Any] = {}
    execution_bridge_summary: Dict[str, Any] = {}
    engine_registry_summary: Dict[str, Any] = {}
    capability_registry_summary: Dict[str, Any] = {}
    tool_registry_summary: Dict[str, Any] = {}
    tool_routing_summary: Dict[str, Any] = {}
    workspace_boundary_summary: Dict[str, Any] = {}
    path_migration_summary: Dict[str, Any] = {}
    terminal_summary: Dict[str, Any] = {}
    browser_research_summary: Dict[str, Any] = {}
    full_automation_summary: Dict[str, Any] = {}
    execution_policy_summary: Dict[str, Any] = {}
    system_health_summary: Dict[str, Any] = {}
    system_health_report_path: Optional[str] = None
    dispatch_plan: Dict[str, Any] = {}
    dispatch_plan_summary: Dict[str, Any] = {}
    dispatch_status: Optional[str] = None
    dispatch_result: Dict[str, Any] = {}
    execution_package_id: Optional[str] = None
    execution_package_path: Optional[str] = None
    runtime_execution_status: Optional[str] = None
    automation_status: Optional[str] = None
    automation_result: Dict[str, Any] = {}
    governance_status: Optional[str] = None
    governance_result: Dict[str, Any] = {}
    project_selection_status: Optional[str] = None
    project_selection_result: Dict[str, Any] = {}
    project_lifecycle_status: Optional[str] = None
    project_lifecycle_result: Dict[str, Any] = {}
    enforcement_status: Optional[str] = None
    enforcement_result: Dict[str, Any] = {}
    workflow_route_status: Optional[str] = None
    workflow_route_reason: Optional[str] = None
    review_queue_entry: Dict[str, Any] = {}
    resume_status: Optional[str] = None
    resume_result: Dict[str, Any] = {}
    heartbeat_status: Optional[str] = None
    heartbeat_result: Dict[str, Any] = {}
    scheduler_status: Optional[str] = None
    scheduler_result: Dict[str, Any] = {}
    completion_result: Dict[str, Any] = {}
    recovery_status: Optional[str] = None
    recovery_result: Dict[str, Any] = {}
    reexecution_status: Optional[str] = None
    reexecution_result: Dict[str, Any] = {}
    launch_status: Optional[str] = None
    launch_result: Dict[str, Any] = {}
    autonomous_launch: bool = False
    autonomy_status: Optional[str] = None
    autonomy_result: Dict[str, Any] = {}
    autonomy_stop_rail_status: Optional[str] = None
    autonomy_stop_rail_result: Dict[str, Any] = {}
    autonomy_stop_rail_config: Dict[str, Any] = {}
    autonomy_current_counts: Dict[str, Any] = {}
    autonomy_governance_trace: Dict[str, Any] = {}
    guardrail_status: Optional[str] = None
    guardrail_result: Dict[str, Any] = {}
    autopilot_enabled: bool = False
    autopilot_status: Optional[str] = None
    autopilot_loop_state: Optional[str] = None
    autopilot_last_run_at: Optional[str] = None
    autopilot_next_run_at: Optional[str] = None
    autopilot_current_focus: Optional[str] = None
    autopilot_requires_operator_review: bool = False
    mission_packet: Dict[str, Any] = {}
    mission_id: Optional[str] = None
    mission_type: Optional[str] = None
    mission_title: Optional[str] = None
    mission_objective: Optional[str] = None
    mission_scope_boundary: Dict[str, Any] = {}
    mission_allowed_actions: List[str] = []
    mission_forbidden_actions: List[str] = []
    mission_allowed_executors: List[str] = []
    mission_risk_level: Optional[str] = None
    mission_success_criteria: Dict[str, Any] = {}
    mission_stop_conditions: List[str] = []
    mission_status: Optional[str] = None
    mission_created_at: Optional[str] = None
    mission_started_at: Optional[str] = None
    mission_completed_at: Optional[str] = None
    mission_failed_at: Optional[str] = None
    mission_requires_initial_approval: bool = True
    mission_requires_final_approval: bool = True
    mission_stop_condition_hit: bool = False
    mission_stop_condition_reason: Optional[str] = None
    mission_escalation_required: bool = False
    executor_route: Optional[str] = None
    executor_route_reason: Optional[str] = None
    executor_route_confidence: float = 0.0
    executor_route_status: Optional[str] = None
    executor_task_type: Optional[str] = None
    executor_task_packet: Dict[str, Any] = {}
    executor_fallback_route: Optional[str] = None
