import Link from "next/link";

export default function TermsPage() {
  return (
    <main
      style={{
        minHeight: "100vh",
        backgroundColor: "black",
        color: "white",
        fontFamily: "sans-serif",
        padding: "40px 20px",
      }}
    >
      <div style={{ maxWidth: "800px", margin: "0 auto", lineHeight: 1.7 }}>
        <h1>Terms of Service</h1>

        <p>
          These Terms of Service are placeholder MVP terms for NegotiateAI.
        </p>

        <h2>1. Informational Use Only</h2>
        <p>
          NegotiateAI provides communication suggestions for informational
          purposes only and does not constitute legal, financial, or
          professional advice.
        </p>

        <h2>2. User Responsibility</h2>
        <p>
          You are responsible for reviewing, editing, and deciding whether to
          use any output generated by the tool.
        </p>

        <h2>3. No Guarantee</h2>
        <p>
          We do not guarantee any negotiation outcome, savings amount, job
          result, or business result.
        </p>

        <h2>4. Prohibited Use</h2>
        <p>
          You may not use this service to support threats, harassment, scams,
          fraud, impersonation, blackmail, coercion, or unlawful conduct.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          NegotiateAI is provided on an as-is basis. To the maximum extent
          allowed by law, the service provider is not liable for losses,
          damages, or decisions made based on generated suggestions.
        </p>

        <h2>6. Changes</h2>
        <p>
          These terms may be updated as the product evolves from MVP to public
          release.
        </p>

        <p style={{ marginTop: "30px" }}>
          <Link href="/" style={{ color: "#7dd3fc" }}>
            Back to home
          </Link>
        </p>
      </div>
    </main>
  );
}