from core.studio_config import (
    PROJECTS_DIR,
    LOGICAL_PROJECT_NAMES,
    PROJECT_FOLDER_MAP,
)


def _project_path(folder_name: str) -> str:
    return str((PROJECTS_DIR / folder_name).resolve())


PROJECTS = {
    "jarvis": {
        "name": LOGICAL_PROJECT_NAMES["jarvis"],
        "path": _project_path(PROJECT_FOLDER_MAP["jarvis"]),
        "workspace_type": "internal",
        "agents": [
            "architect",
            "coder",
            "tester",
            "docs",
            "executor",
            "workspace",
            "operator",
            "supervisor",
        ],
        "description": "Long-term personal AI assistant and orchestration platform managed inside Forge.",
    },
    "paragon": {
        "name": LOGICAL_PROJECT_NAMES["paragon"],
        "path": _project_path(PROJECT_FOLDER_MAP["paragon"]),
        "workspace_type": "internal",
        "agents": [
            "architect",
            "coder",
            "tester",
            "docs",
            "executor",
            "workspace",
            "operator",
            "supervisor",
        ],
        "description": "AI negotiation and communication copilot product.",
    },
    "epoch": {
        "name": LOGICAL_PROJECT_NAMES["epoch"],
        "path": _project_path(PROJECT_FOLDER_MAP["epoch"]),
        "workspace_type": "internal",
        "agents": [
            "architect",
            "coder",
            "tester",
            "docs",
            "executor",
            "workspace",
            "operator",
            "supervisor",
        ],
        "description": "Civilization and future simulation engine.",
    },
    "genesis": {
        "name": LOGICAL_PROJECT_NAMES["genesis"],
        "path": _project_path(PROJECT_FOLDER_MAP["genesis"]),
        "workspace_type": "internal",
        "agents": [
            "architect",
            "coder",
            "tester",
            "docs",
            "executor",
            "workspace",
            "operator",
            "supervisor",
        ],
        "description": "AI world and environment generator.",
    },
    "game_dev": {
        "name": LOGICAL_PROJECT_NAMES["game_dev"],
        "path": _project_path(PROJECT_FOLDER_MAP["game_dev"]),
        "workspace_type": "internal",
        "agents": [
            "architect",
            "coder",
            "tester",
            "docs",
            "executor",
            "workspace",
            "operator",
            "supervisor",
        ],
        "description": "General game development workspace.",
    },
    "rpg_project": {
        "name": LOGICAL_PROJECT_NAMES["rpg_project"],
        "path": _project_path(PROJECT_FOLDER_MAP["rpg_project"]),
        "workspace_type": "internal",
        "agents": [
            "architect",
            "coder",
            "tester",
            "docs",
            "executor",
            "workspace",
            "operator",
            "supervisor",
        ],
        "description": "RPG-specific game project workspace.",
    },
    "vector": {
        "name": LOGICAL_PROJECT_NAMES["vector"],
        "path": _project_path(PROJECT_FOLDER_MAP["vector"]),
        "workspace_type": "internal",
        "agents": [
            "architect",
            "coder",
            "tester",
            "docs",
            "executor",
            "workspace",
            "operator",
            "supervisor",
        ],
        "description": "Trading systems and automation workspace.",
    },
}